# Generated by Django 4.1.4 on 2023-01-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
